name: Tests

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  rubocop:
      name: Run Tests
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-ruby@v1
          with:
            ruby-version: 3.1
        - name: Install dependencies
          run: bundle install 
        - name: Run tests
          run: bundle exec rspec